apiVersion: v1
kind: Service
metadata:
  name: infraops-backend
  namespace: {{ .Values.namespace }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /api/monitoring/metrics
    prometheus.io/port: "8000"
spec:
  selector:
    app: infraops-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infraops-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: infraops-backend
  template:
    metadata:
      labels:
        app: infraops-backend
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infraops-secret
                  key: MYSQL_PASSWORD
            - name: DATABASE_URL
              value: mysql+pymysql://{{ .Values.mariadb.user }}:$(MYSQL_PASSWORD)@infraops-mariadb:3306/{{ .Values.mariadb.database }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: infraops-secret
                  key: JWT_SECRET
          envFrom:
            - configMapRef:
                name: infraops-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 45
            periodSeconds: 20
          resources:
{{ toYaml .Values.backend.resources | indent 12 }}
