apiVersion: v1
kind: Service
metadata:
  name: infraops-mariadb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: infraops-mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: infraops-mariadb
  namespace: {{ .Values.namespace }}
spec:
  serviceName: infraops-mariadb
  replicas: 1
  selector:
    matchLabels:
      app: infraops-mariadb
  template:
    metadata:
      labels:
        app: infraops-mariadb
    spec:
      containers:
        - name: mariadb
          image: {{ .Values.mariadb.image }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.database }}
            - name: MYSQL_USER
              value: {{ .Values.mariadb.user }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infraops-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infraops-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command: ["healthcheck.sh", "--connect", "--innodb_initialized"]
            initialDelaySeconds: 25
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["healthcheck.sh", "--connect", "--innodb_initialized"]
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
{{ toYaml .Values.mariadb.resources | indent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: mariadb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.mariadb.storage }}
