apiVersion: v1
kind: Secret
metadata:
  name: infraops-secret
  namespace: infraops
type: Opaque
stringData:
  MYSQL_PASSWORD: root@1234
  MYSQL_ROOT_PASSWORD: root@1234
  JWT_SECRET: 6894f0a0c05697ac771dfc5f1d1749cdc2c7cbbfdd777471c1721bec8bf0b3fc

