apiVersion: v1
kind: Secret
metadata:
  name: infraops-secret
  namespace: infraops
type: Opaque
stringData:
  MYSQL_PASSWORD: change-this-db-password
  MYSQL_ROOT_PASSWORD: change-this-root-password
  JWT_SECRET: change-this-jwt-secret-before-production
