apiVersion: v1
kind: ConfigMap
metadata:
  name: infraops-config
  namespace: {{ .Values.namespace }}
data:
  APP_NAME: InfraOps Portal API
  ENVIRONMENT: production
  API_PREFIX: /api
  CORS_ORIGINS: http://{{ .Values.ingress.host }}
  MYSQL_DATABASE: {{ .Values.mariadb.database }}
  MYSQL_USER: {{ .Values.mariadb.user }}
