apiVersion: v1
kind: Secret
metadata:
  name: infraops-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MYSQL_PASSWORD: {{ .Values.mariadb.password | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mariadb.rootPassword | quote }}
  JWT_SECRET: {{ .Values.backend.jwtSecret | quote }}
